### PR TITLE
Introduce Consumer interfaces

### PR DESCRIPTION
**Pull request by tomsik68**
This PR introduces Consumer interfaces. Consumers are responsible for processing values received by importer. There is a separate interface for each accounting data record (IP, VM, Storage), so they can be implemented separately in case of need.

Apart from that, this PR adds a dummy implementation of all three interfaces called `Writer`. This will be later used to write processing results into files as desired.

This PR depends on #6. Please merge it before and I'll rebase on master. I just wanted to submit it for review.

### CODE REVIEW

**Review by amarthadan — COMMENTED** [review]
This looks good and I like the direction it's going :+1:

I know it's still a work in progress so maybe my comments will be useless but I want us to be on the same page.

First of all, I can already tell you that VM records will be in APEL 0.4 format (a made up format, basically `key: value` on each line), which is an ideal candidate for use of templates and IP records will be in JSON, which (in case of matching keys) doesn't need to be generated via templates. But I guess you know that already and that's why you came up with consumer interfaces.

But this will have to be somehow configurable, probably just in configuration file, it would be a nightmare in CLI. So you have to create a configuration file that would allow to set different processing (consumer and its options I suppose) for each record type (vm, IP, storage). So I don't mind forcing the user to set `--template-dir` for the time being but it is likely to change in the future. Or do you have other plans?

**Comment by tomsik68** [comment]
It's always useful to clarify goals - especially while it's work in progress :smile:

The consumer interfaces were designed like that because I had no idea what the output would look like (single file vs multiple files, file format, ...), so I wanted to have the option to implement a consumer for each type of record separately.

About `-templates-dir`: Initially, I only knew some records would be in APEL format, so I thought they would use "some plaintext format" for all types of records. That's why I thought `-templates-dir` would be useful for any filetype. Now that I hear about JSON, it looks like it won't be required in case different consumers are used. I will add configuration sections for individual consumers rather than CLI options.

One thing I didn't really consider is to have a configuration option that allows users to choose consumer implementations. I thought we would just use one of them in the end. It's not a problem, but it's very good you made me aware of this at this point in development :+1:

**Comment by amarthadan** [comment]
You are right! I'm once again overengineering it :smile: We had similar feature in `oneacct-export` and nobody ever used it :smile:

So we'll do it like you said. No special configuration for each record type, we will just use consumer suitable for each record type. Nobody will ever want/need to produce one record type in multiple formats.

**Review by amarthadan — DISMISSED** [review]
:satellite:

**Review by amarthadan — APPROVED** [review]

**Pull request merged**
